### ISSUE TITLE
Support RBAC in a generic way

### ISSUE THREAD

**Issue by csviri** [quarkiverse/quarkus-operator-sdk#696] opened 2023-08-23 07:50 UTC
Currently roles and role bindings for secondary resources are generated based on managed dependent resources. While this is good, there are cases when managed dependent resources are not sufficient to cover the logic of the controller, but the roles / bindings for secondary resource we still want to generate. 

One way to handle this is to introduce **annotations** for the reconciler that will provide all the necessary information to generate rbac roles and bindings.

See how it works in kubebuilder: https://book.kubebuilder.io/reference/markers/rbac.html?highlight=rbac#rbac

**Comment by csviri** [comment] 2023-08-23 08:07
Note that this is not just for helm, for all the generated artifacts, like `kubernetes.yaml` and possibly OLM

**Comment by metacosm** [comment] 2023-08-31 10:48
@Jeansen could you try #701 to see if this fits your needs, take a look at [the `SimpleReconciler` class for an example ](https://github.com/quarkiverse/quarkus-operator-sdk/commit/2c94b5eba980bdddf71dc7d39c8a027a66bca7dc#diff-03ba60732090f2c338c764b64c239e661834efa3d53df0cd2bffea8d652f68aeR11-R12) of how to use the feature.

**Comment by Jeansen** [comment] 2023-08-31 19:43
@metacosm Oh, great. I'll check it out and report back.

**Comment by Jeansen** [comment] 2023-08-31 21:30
@metacosm Hm..I do not see any effect. I've cloned the repo. switched to the `additional-rbac` branch and did `mvn clean install`. I then changed the versions in my project accordingly. I could add the annotations from your example. But I do not see any effect in the generated bundle or manifest files. Maybe I am missing something? I've pushed my changes in https://github.com/Jeansen/cert-operator .

**Comment by metacosm** [comment] 2023-09-01 07:25
I'm not familiar with Gradle but trying it out your project, it didn't seem to pick up my just built snapshot from my local maven repository, so that might explain why you're not seeing changes as Gradle might pick the snapshot from a remote repository.

**Comment by metacosm** [comment] 2023-09-01 07:31
Found the error: you're using the 6.3.0 version of the BOM. Changing that version to 6.3.1-SNAPSHOT fixes the problem and the additional rules do properly show up. I don't know what's Gradle way to deal with this but you should import the BOM and not have explicit versions on the QOSDK dependencies anywhere else, otherwise this causes issues as just seen.

**Comment by metacosm** [comment] 2023-09-01 07:32
That said, checking things out again allowed me to find an issue so it's all good :)

**Comment by Jeansen** [comment] 2023-09-01 07:34
> Found the error: you're using the 6.3.0 version of the BOM. Changing that version to 6.3.1-SNAPSHOT fixes the problem and the additional rules do properly show up. I don't know what's Gradle way to deal with this but you should import the BOM and not have explicit versions on the QOSDK dependencies anywhere else, otherwise this causes issues as just seen.

Well, actually - to my understanding - I gave the versions only to those dependencies I wanted to test and keep the rest as is. But well ... lessons learned ;-)

**Comment by Jeansen** [comment] 2023-09-01 07:38
> That said, checking things out again allowed me to find an issue so it's all good :)

OK. I've no compiled again with the BOM set correctly and it works. I'll tinker a bit more in the evening.

What issue did you find? Anything I should look out for?

**Comment by metacosm** [comment] 2023-09-01 07:39
> > Found the error: you're using the 6.3.0 version of the BOM. Changing that version to 6.3.1-SNAPSHOT fixes the problem and the additional rules do properly show up. I don't know what's Gradle way to deal with this but you should import the BOM and not have explicit versions on the QOSDK dependencies anywhere else, otherwise this causes issues as just seen.
> 
> Well, actually - to my understanding - I gave the versions only to those dependencies I wanted to test and keep the rest as is. But well ... lessons learned ;-)

Looking at it again: the problem is that you weren't overriding all the dependencies that needed to be replaced, most importantly the core-deployment one, which is where the "magic" happens :)

**Comment by metacosm** [comment] 2023-09-01 07:41
> > That said, checking things out again allowed me to find an issue so it's all good :)
> 
> OK. I've no compiled again with the BOM set correctly and it works. I'll tinker a bit more in the evening.
> 
> What issue did you find? Anything I should look out for?

It should already be fixed: the problem was that the code wasn't handling a single `RBACRule` annotation properly, it only worked if you had multiple ones. This is fixed by https://github.com/quarkiverse/quarkus-operator-sdk/pull/701/commits/d3bbadb4638636f024c2678a5557f347f6174a3c

**Comment by Jeansen** [comment] 2023-09-01 07:56
OK then. I'll play with it more this evening and try out more. Thank you very much for your input, help and efforts.

**Comment by Jeansen** [comment] 2023-09-01 17:56
So, I've successfully added some more annotations, build and bundled everything and deployed it via OPM. Rocks like a guitar :-D

**Comment by metacosm** [comment] 2023-09-02 12:17
Thanks for the update!

**Closed** 2023-09-02 12:19 UTC
